version: '3'
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 # puerto interno y puerto externo para bd
    environment:
      MONGODB_DATABASE: nest-pokemon # nombre bd
    volumes:
      - ./mongo:/data/db # bd persistente